
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nontancafe_development

test:
  <<: *default
  database: nontancafe_test

production:
  <<: *default
  database: nontancafe_production
  username: nontancafe
  password: <%= ENV['NONTANCAFE_DATABASE_PASSWORD'] %>
